// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcepzqttupuskxkjmugm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZXB6cXR0dXB1c2t4a2ptdWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTUxNDksImV4cCI6MjA1OTA5MTE0OX0._9EW4AoKmCyzjwe8APRI6__DpBqxwRfW-a2cXwdmpcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);